spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/transport_tracker
spring.datasource.username=root
spring.datasource.password=abi@Mysql123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
